### ISSUE TITLE
Update npm package automatically after increasing version in package.json

### ISSUE THREAD

**Issue by Kouprin** [near/rainbow-bridge-lib#3]
Currently we need to do it manually.
The steps are:
- create a new npm user (or use boatnear if it can be used for this purpose)
- add a hook that starts deployment process automatically right after changing the version
- add the same for -sol and -rs repos

**Comment by ailisp** [comment]
Duplicate with: https://github.com/near/rainbow-bridge-cli/issues/327, I'll merge your step with that one
